// src/utils/config.ts
// Persists and reads MI configuration (.env file in the project directory).
// Docker Compose natively reads .env from the project directory,
// so writing MI_DOCKERFILE and MI_VERSION here means all compose commands
// (up, build, ps, logs) automatically pick up the right values.

import fs from "fs-extra";
import path from "path";
import { getProjectRoot } from "./files.js";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────
export type MiSource = "dockerhub" | "local";

export interface MiConfig {
  miSource: MiSource;
  miDockerfile: string;   // "Dockerfile.dockerhub" or "Dockerfile"
  miVersion: string;      // e.g. "4.5.0", "4.5.0-alpine"
}

export interface DetectedZip {
  version: string;
  path: string;
  location: "mcp-server-root" | "project-build-context";
}

// Default MI version — single source of truth.
// Update this constant (and DOCKERHUB_VERSIONS) when WSO2 publishes new images.
export const DEFAULT_MI_VERSION = "4.5.0";

// Known Docker Hub versions
export const DOCKERHUB_VERSIONS = [
  "4.3.0",
  "4.4.0",
  "4.5.0",
];
export const DOCKERHUB_VARIANTS = ["-alpine", "-rocky"];

// ─────────────────────────────────────────────────────────────────────────────
// Map between user-facing miSource and internal Dockerfile name
// ─────────────────────────────────────────────────────────────────────────────
export function sourceToDockerfile(source: MiSource): string {
  return source === "local" ? "Dockerfile" : "Dockerfile.dockerhub";
}

export function dockerfileToSource(dockerfile: string): MiSource {
  return dockerfile === "Dockerfile" ? "local" : "dockerhub";
}

// ─────────────────────────────────────────────────────────────────────────────
// Write .env to the project directory
// ─────────────────────────────────────────────────────────────────────────────
export async function writeConfig(projectDir: string, config: MiConfig): Promise<void> {
  const envPath = path.join(projectDir, ".env");
  const content = [
    "# Generated by kafka-mi-mcp-server — do not edit manually",
    `# MI source: ${config.miSource}`,
    `MI_DOCKERFILE=${config.miDockerfile}`,
    `MI_VERSION=${config.miVersion}`,
    "",
  ].join("\n");
  await fs.ensureDir(projectDir);
  await fs.writeFile(envPath, content, "utf8");
}

// ─────────────────────────────────────────────────────────────────────────────
// Read .env from the project directory
// ─────────────────────────────────────────────────────────────────────────────
export async function readConfig(projectDir: string): Promise<MiConfig | null> {
  const envPath = path.join(projectDir, ".env");
  if (!(await fs.pathExists(envPath))) return null;

  const content = await fs.readFile(envPath, "utf8");
  const vars: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq > 0) {
      vars[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
    }
  }

  const miDockerfile = vars["MI_DOCKERFILE"] ?? "Dockerfile.dockerhub";
  const miVersion = vars["MI_VERSION"] ?? DEFAULT_MI_VERSION;
  return {
    miSource: dockerfileToSource(miDockerfile),
    miDockerfile,
    miVersion,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Detect local wso2mi-*.zip files in both the MCP server root and the
// project's wso2mi/ build context directory
// ─────────────────────────────────────────────────────────────────────────────
export async function detectLocalZips(projectDir?: string): Promise<DetectedZip[]> {
  const results: DetectedZip[] = [];
  const versionRegex = /^wso2mi-(.+)\.zip$/;

  // 1. Scan MCP server project root
  const root = getProjectRoot();
  try {
    const rootFiles = await fs.readdir(root);
    for (const file of rootFiles) {
      const m = versionRegex.exec(file);
      if (m) {
        results.push({
          version: m[1],
          path: path.join(root, file),
          location: "mcp-server-root",
        });
      }
    }
  } catch { /* dir may not exist */ }

  // 2. Scan project build context (wso2mi/ subdir)
  if (projectDir) {
    const buildCtx = path.join(projectDir, "wso2mi");
    try {
      const ctxFiles = await fs.readdir(buildCtx);
      for (const file of ctxFiles) {
        const m = versionRegex.exec(file);
        if (m) {
          // Avoid duplicates if same version already found in root
          const alreadyFound = results.some(r => r.version === m![1]);
          if (!alreadyFound) {
            results.push({
              version: m[1],
              path: path.join(buildCtx, file),
              location: "project-build-context",
            });
          }
        }
      }
    } catch { /* dir may not exist yet */ }
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// Format config for display
// ─────────────────────────────────────────────────────────────────────────────
export function formatConfig(config: MiConfig): string {
  if (config.miSource === "local") {
    return `Local MI pack (wso2mi-${config.miVersion}.zip)`;
  }
  return `Docker Hub (wso2/wso2mi:${config.miVersion})`;
}
